### PR TITLE
Update us-dockerflix-sniproxy.conf

### PR DESCRIPTION
**Pull request by random-robbie**
proxy anything that hits sniproxy docker.

### CODE REVIEW

**Comment by trick77** [comment]
I think that is more harmful than helpful unless you lock down the server using other means because what you're doing is creating an open proxy for everyone to use. This is asking for a lot of trouble.

**Comment by random-robbie** [comment]
i think an iptables firewall solution would be best to resolve that or some easier way to manage the domains in the sniproxy config file.

**Comment by trick77** [comment]
I'm not going to do it this way, it's too complicated for most users.

**Comment by random-robbie** [comment]
will revert my changes in my fork and need to add a few domains to the list.

**Comment by trick77** [comment]
Sure, just send them along and I will add them. And you can obviously wildcard it in your fork if you like to do so, I just don't want to do it in the main project because it could end up badly for some users.

**Pull request closed without merging**
