### PR TITLE
Add one stat HBO GO server and add its metion to README since it was …

### PR DESCRIPTION
**Pull request by bnowakow**
Some minor clarification per our conversation back on 10th of May (-;

### CODE REVIEW

**Comment by trick77** [comment]
Thanks man. Did you omit the sniproxy config entry on purpose?

**Comment by bnowakow** [comment]
Nope, I've missed that!
Fixed in d5c03af0a498516d3da9283fec01ba9f5fa88b17

**Comment by trick77** [comment]
You know what, I don't think it's required. The big boys aren't doing it as well:

Unblock:
drfalken@wopr:~# dig @208.122.23.23 hbobroadband.sc.omtrdc.net +short
192.243.250.84
192.243.250.68

Level 3 Public DNS:
drfalken@wopr:~# dig @4.2.2.1 hbobroadband.sc.omtrdc.net +short
192.243.250.84
192.243.250.68

**Comment by bnowakow** [comment]
Ok. Should I just limit changes only to mentions in README.mk?

**Comment by trick77** [comment]
That would be cool. Did you test it in the browser only or some standalone players as well?

**Comment by bnowakow** [comment]
Should I create separate branch to rebase -i it properly or you don't mind additional commits in the process? (didn't try to do push --force on already submitted PR too [; )

I did test it only on browser since my iPhone and Apple TV doesn't support dnsmasq yet (-;

**Comment by trick77** [comment]
Just pushed it to master ;-)

**Comment by bnowakow** [comment]
Than it concludes this PR. Thx once again for this wonderful Docker image! (-;
Merged in f06bcc4776fec9f65edb67c5da994050e23246a2

**Pull request closed without merging**
